builds:
  - binary: zodo
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: zodo
    homepage: https://github.com/longmenzhitong/zodo
    tap:
      owner: longmenzhitong
      name: homebrew-longmenzhitong
    commit_author:
      name: longmenzhitong
      email: longmenzhitong@gmail.com

checksum:
  name_template: "checksums.txt"
